// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMz0ztT56KE_LNF3C_uPERlrfjHg18Ps',
    appId: '1:524817647805:web:5d2424b70d40209362cfd4',
    messagingSenderId: '524817647805',
    projectId: 'fair-bangla',
    authDomain: 'fair-bangla.firebaseapp.com',
    storageBucket: 'fair-bangla.firebasestorage.app',
    measurementId: 'G-W5JYRC62HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQqlx-U57ox-Ce1sz2ZAcSUzdu94Rih4',
    appId: '1:524817647805:android:23cbb95f5bd6a72162cfd4',
    messagingSenderId: '524817647805',
    projectId: 'fair-bangla',
    storageBucket: 'fair-bangla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOKFZApk3rL3qeRRuEgY20grPojZDg5c4',
    appId: '1:524817647805:ios:65450c49328fd00d62cfd4',
    messagingSenderId: '524817647805',
    projectId: 'fair-bangla',
    storageBucket: 'fair-bangla.firebasestorage.app',
    iosBundleId: 'com.example.fairBangla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOKFZApk3rL3qeRRuEgY20grPojZDg5c4',
    appId: '1:524817647805:ios:65450c49328fd00d62cfd4',
    messagingSenderId: '524817647805',
    projectId: 'fair-bangla',
    storageBucket: 'fair-bangla.firebasestorage.app',
    iosBundleId: 'com.example.fairBangla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMz0ztT56KE_LNF3C_uPERlrfjHg18Ps',
    appId: '1:524817647805:web:f12cbb63f8142eec62cfd4',
    messagingSenderId: '524817647805',
    projectId: 'fair-bangla',
    authDomain: 'fair-bangla.firebaseapp.com',
    storageBucket: 'fair-bangla.firebasestorage.app',
    measurementId: 'G-T5Y1NMSV0V',
  );
}
